name: publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
          node-version: 18
          cache: 'npm'
          
    - name: Install dependencies
      run: |
        npm install
    
    - name: Publish Npm Package
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: | 
        bash ./scripts/publish.sh